name: Repository Configuration Validator

on:
  push:
    paths:
      - 'repositories/*.yml'
  pull_request:
    paths:
      - 'repositories/*.yml'
  workflow_dispatch:

jobs:
  validate-repository-config:
    runs-on: ubuntu-latest
    environment: 
        name: cloud-platform
      
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub PyYAML
    
    - name: Validate Repository Configuration
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        GITHUB_ORGANIZATION: ${{ github.repository_owner }}
      run: |
        python .github/scripts/repo_configuration_management.py